import type { CourseModule } from "../types";

export const module5: CourseModule = {
  slug: "module-5-mourning-and-releasing",
  title: "Mourning and Releasing",
  eyebrow: "Module 5",
  summary:
    "Judith Herman calls this stage 'necessary but dreaded.' The old life — the years spent as the wrong person, the relationships shaped by the old code, the version of you that coped instead of lived — has to be mourned before the new one can be built. And the root belief has to be rewritten through the brain's own update mechanism: memory reconsolidation.",
  lessons: [
    {
      slug: "5-1-the-grief-of-the-unlived-life",
      title: "The Grief of the Unlived Life",
      eyebrow: "Lesson 5.1",
      reading: "25 minutes of practice",
      blocks: [
        {
          type: "script",
          text: "There is a grief that most programs in this space skip over entirely. The grief of the unlived life.\n\nYou have been carrying a program that was never yours. The decisions you made from inside that program — the relationships you stayed in, the ones you walked away from, the work you chose, the ways you shrank, the moments you did not speak — were all generated by code you did not write.\n\nThat is a real loss. And it has to be grieved.\n\nNot because the grief changes the past. Because the grief is the body's way of releasing its attachment to the old identity. Without the mourning, the old identity stays tethered. You can install a new program on top of it, and it will feel like progress for a few weeks, and then the old one will reassert itself because the body never let go.\n\nThe letting go is the grief. The grief is the release. And the release is the condition the new identity requires.",
        },
        {
          type: "tool",
          tool: "vision-letter",
          title: "A letter from your future self",
          description:
            "Write a letter from the version of you one year from now — the version who has done the work, who lives as the person the old code would not allow — to the version of you sitting here today. What does she want you to know about the grief? What does she want you to know about what comes after it?",
          timeframe: "one year from today",
          storageKey: "cert-5-1-future-letter",
        },
        {
          type: "tool",
          tool: "writing-prompt",
          title: "What you lost while the old program was running",
          prompt:
            "Name the specific things you lost. Not in general. Specifically. A relationship. A decision. A year. A version of yourself you glimpsed once and then edited away. Name them so the body can release them.",
          placeholder: "What I lost while the old program was running:\n\n",
          minRows: 10,
          storageKey: "cert-5-1-what-i-lost",
        },
      ],
    },

    {
      slug: "5-2-the-reconsolidation-window",
      title: "Memory Reconsolidation — The Brain's Update Mechanism",
      eyebrow: "Lesson 5.2",
      reading: "30 minutes of practice",
      blocks: [
        {
          type: "script",
          text: "In the year 2000, Nader, Schafe, and LeDoux published the research that changed everything about how we understand belief change.\n\nThey proved that a consolidated memory — a belief stored in long-term memory — can be permanently rewritten under three specific conditions, met in sequence.\n\nCondition one. The old belief has to be reactivated. Not remembered intellectually — felt in the body. The emotional state that lives with the belief has to be live in the system right now.\n\nCondition two. While it is live, the brain has to encounter a mismatch. Something that contradicts what the belief was predicting would happen. Not a counter-argument. An experience that violates the expectation.\n\nCondition three. The mismatch has to be held for long enough that the brain registers it as not-an-error.\n\nWhen all three are present in sequence, the belief is rewritten at the level where it was originally stored. This is memory reconsolidation. It is the brain's own mechanism for updating what it has learned. And it is the neuroscience behind why the practices in this module produce permanent change rather than temporary relief.",
        },
        {
          type: "tool",
          tool: "reconsolidation",
          title: "The guided reconsolidation hold",
          description:
            "Bring the old state forward (the root belief from Module 4, felt in the body). Bring the new state forward (the version of you without fear). Hold both in the same body at the same time for three minutes. The brain registers the coexistence. The old belief updates with the new data.",
          storageKey: "cert-5-2-reconsolidation",
        },
        {
          type: "note",
          text: "The reconsolidation hold is the hinge of the entire program. Everything before it was preparation for this moment. Everything after it is installation of what was made possible by it. Do not rush through it. Do it in a quiet room, phone off, and give the body time afterward to integrate.",
        },
      ],
    },

    {
      slug: "5-3-the-installation-protocol",
      title: "The Full Installation Protocol",
      eyebrow: "Lesson 5.3",
      reading: "35 minutes of practice",
      blocks: [
        {
          type: "script",
          text: "The complete sequence for permanent subconscious change, in order.\n\nFirst, nervous system regulation. The settle from Module 1. You cannot install new code from a threat state.\n\nSecond, heart coherence. The gate from Module 2. The heart and the mind must be broadcasting the same signal.\n\nThird, reactivation of the old belief. Felt in the body. The somatic marker from Module 4.\n\nFourth, the contradicting experience. The new identity state — the version of you without fear — held in the same body at the same time. The reconsolidation window.\n\nFifth, somatic anchoring. The new identity must be felt in the body, not just understood in the mind. A specific location, a specific sensation, a specific posture.\n\nSixth, repetition. The Quantum Zeno Effect — the physics principle that consistent observation of a quantum state prevents it from reverting to a previous state. The daily protocol.\n\nAll six. In sequence. This is the engineering.",
        },
        {
          type: "tool",
          tool: "heart-coherence",
          title: "Step 1–2: Settle + Coherence gate",
          description:
            "The first five minutes. Settle into ventral. Then enter heart coherence. This opens the door for the installation.",
          durationSeconds: 300,
          storageKey: "cert-5-3-gate",
        },
        {
          type: "tool",
          tool: "reconsolidation",
          title: "Steps 3–5: The full reconsolidation hold",
          description:
            "Old state forward. New state forward. Hold both. Three-minute window. Then capture what shifted. This is the installation.",
          storageKey: "cert-5-3-full-reconsolidation",
        },
        {
          type: "tool",
          tool: "mantra-installer",
          title: "Step 6: The repetition — one sentence installed",
          description:
            "Write the single present-tense sentence that carries the new identity. The installer paces your breath around it for ten slow repetitions. This is the Quantum Zeno Effect in practice.",
          repeats: 10,
          storageKey: "cert-5-3-mantra",
        },
      ],
    },
  ],
};
