// Sacred Sovereign Subliminals — a hand-authored library of identity
// phrases that the SubliminalPlayer speaks softly over theta audio and
// an optional ambient soundscape (rain, ocean, forest, solfeggio tone).
//
// All audio is synthesized live in the browser via Web Audio and
// spoken live via ElevenLabs (or the browser fallback). Zero files.
// Works offline once the page has loaded.

import type { AmbientKind, SolfeggioFrequency } from "@/lib/audio/ambient";

export type SubliminalTrack = {
  slug: string;
  title: string;
  description: string;
  durationMinutes: number;
  beatFrequency: number; // 4..8
  ambient?: AmbientKind;
  solfeggio?: SolfeggioFrequency;
  phrases: string[];
};

export const SUBLIMINALS: SubliminalTrack[] = [
  {
    slug: "i-am-already-her",
    title: "I am already her",
    description:
      "Identity install for the hypnagogic threshold. Put this on as you drift to sleep and let every phrase find a place to land.",
    durationMinutes: 22,
    beatFrequency: 6,
    ambient: "rain",
    solfeggio: 528,
    phrases: [
      "I am already her.",
      "My body is the home I was always meant to live in.",
      "The person I have been waiting to become is already here.",
      "I walk through my life as the one I actually am.",
      "I am safe in the quiet. I am safe in the becoming.",
      "Every breath brings me back to who I was before the fear.",
      "I do not have to prove anything to be her. I only have to let her.",
      "The field is already arranging itself around my true state.",
      "What is mine is already on its way to me.",
      "I am the one I have been looking for.",
      "My spine is tall and my shoulders are soft.",
      "I take up exactly as much space as I need.",
      "I am allowed to move at my own pace.",
      "My body does not need to brace anymore.",
      "I am no longer editing myself to fit smaller rooms.",
      "The old version of me is welcome to rest now.",
      "I receive what comes to me without guilt.",
      "I do not chase what is already mine.",
      "Every room I walk into becomes warmer because I am in it.",
      "I trust what my body is telling me.",
      "I choose the version of me that is soft and sovereign at once.",
      "I am not in a hurry. I am already arrived.",
      "My presence is enough. My presence has always been enough.",
      "I am allowed to be whole today.",
      "I am already her. I have always been her.",
    ],
  },

  {
    slug: "my-body-is-safe-now",
    title: "My body is safe now",
    description:
      "For the nervous system that has been in low-grade activation for a very long time. Listen in a room where nothing is asked of you.",
    durationMinutes: 20,
    beatFrequency: 5,
    ambient: "ocean",
    solfeggio: 396,
    phrases: [
      "My body is safe now.",
      "The scan can stop. I am here.",
      "My shoulders can come down. My jaw can let go.",
      "I am allowed to rest inside my own body.",
      "Nothing in this room is asking anything of me.",
      "My breath is mine. My quiet is mine.",
      "The old alarm was for an old moment. That moment has passed.",
      "I do not need to brace to be held.",
      "My nervous system is learning it is safe to soften.",
      "I am coming home to a body that was always mine.",
      "Every exhale is an exhale of something old.",
      "I am allowed to rest even when the work is not done.",
      "My body has done enough holding today.",
      "The ground is holding me. I do not have to hold myself up.",
      "I release what I was carrying that was never mine to carry.",
      "Each cell in my body is listening. Each cell is safe.",
      "I give my nervous system permission to come down.",
      "Softness is not weakness. Softness is the new default.",
      "There is no threat here. My body is allowed to know that.",
      "I am safer than I have felt in a long time.",
      "My body is allowed to forget how to brace.",
      "The vigilance was for survival. I am not in survival anymore.",
      "I am home. My body is home. My home is safe.",
      "I release the old fight. I release the old flight.",
      "I am held. I am held. I am held.",
    ],
  },

  {
    slug: "the-return-is-the-practice",
    title: "The return is the practice",
    description:
      "For the day the old version pulled you back. Listen without guilt in the first sixty seconds of the return.",
    durationMinutes: 18,
    beatFrequency: 6,
    ambient: "rain",
    solfeggio: 639,
    phrases: [
      "The return is the practice.",
      "I have not lost anything by drifting.",
      "The moment I notice the drift, I am already back.",
      "My speed of return is the only metric that matters.",
      "The old state is a room I visited. I am not required to stay.",
      "I come back without punishing myself.",
      "Each return is a rewiring.",
      "I am allowed to soften the moment I notice I am hard.",
      "The part of me that noticed is already the new one.",
      "I am here. I am here. I am here.",
      "No drift is permanent. Every return is the work.",
      "I do not have to start over. I just have to arrive.",
      "The old pattern was a visitor. It has left.",
      "My return is not a performance. It is a practice.",
      "I am not disappointed in myself. I am returning.",
      "Returning is enough. Returning is always enough.",
      "I trust the part of me that kept coming back.",
      "Each return rewires the path a little smoother.",
      "I do not need to earn my way back. I just come back.",
      "I am learning the return. That is the whole thing.",
      "My body remembers the way home.",
      "I come back faster every time.",
      "I am not behind. There is no behind.",
      "The return is the practice. I am always practising.",
      "Welcome back. Welcome back. Welcome back.",
    ],
  },

  {
    slug: "i-am-the-observer",
    title: "I am the observer",
    description:
      "For when you need to remember that your state shapes which slice of the field resolves. Best listened to before a morning installation session.",
    durationMinutes: 22,
    beatFrequency: 7,
    ambient: "forest",
    solfeggio: 963,
    phrases: [
      "I am the observer.",
      "The field responds to the state I am actually in.",
      "I do not force the outcome. I become the one the outcome belongs to.",
      "What I hold inside reorganizes what I meet outside.",
      "My inner state and my outer life are one system.",
      "I choose which slice of the field I collapse into today.",
      "The version of me I observe becomes the version that holds.",
      "I am the instrument. I am the tuning. I am the frequency.",
      "Every moment is a measurement. I meet each one as her.",
      "I am the one reality is arranging itself around.",
      "I do not chase. I become.",
      "The field is listening to my state, not my words.",
      "I collapse the version of me that is already the answer.",
      "I am the observer, and the observer decides.",
      "I trust what the field does when I hold the state long enough.",
      "My inner state is the upstream of everything.",
      "I meet the day as the one who has already arrived.",
      "I do not measure myself by the old metrics.",
      "I observe with kindness. I collapse with certainty.",
      "The field is soft when I am soft. It is firm when I am firm.",
      "I am being measured by the universe right now. I am meeting its gaze.",
      "I do not need to explain my state. I only need to hold it.",
      "I collapse the version of me that is already home.",
      "I am the observer. I have always been the observer.",
      "I am here. The field is here. We are one thing.",
    ],
  },

  // ---------- New tracks ----------

  {
    slug: "wealth-without-effort",
    title: "Wealth without effort",
    description:
      "For the person who has confused earning with deserving. A reprogramming of the money script one phrase at a time.",
    durationMinutes: 20,
    beatFrequency: 6,
    ambient: "ocean",
    solfeggio: 528,
    phrases: [
      "I am allowed to receive without earning.",
      "Wealth is a frequency I am already in.",
      "My worth is not measured by effort.",
      "Money comes to me through doors I did not build.",
      "I do not chase money. Money is drawn to my state.",
      "I am safe to hold wealth in my body.",
      "The universe is not running out. I am not late.",
      "I receive with open hands and no apology.",
      "My nervous system can hold abundance now.",
      "I am worthy of rest and wealth at the same time.",
      "Money flows to me through the easiest possible paths.",
      "I do not have to struggle to deserve.",
      "Wealth likes my frequency.",
      "I release the old story that I have to prove I am enough.",
      "My work is already enough. My being is already enough.",
      "Money is a mirror. I am changing the shape of what it reflects.",
      "I am allowed to have ease and wealth at once.",
      "I receive without guilt. I spend without fear.",
      "The part of me that did not believe I deserved this is being replaced.",
      "I hold money the way I hold my own breath — naturally.",
      "Wealth is simply the physical form of my alignment.",
      "I do not need to hustle to be chosen.",
      "Abundance is my default, not my reward.",
      "I am a warm place for wealth to land.",
      "Money is already on its way. I am already her.",
    ],
  },

  {
    slug: "the-heart-that-was-always-enough",
    title: "The heart that was always enough",
    description:
      "For the person who has been trying to earn love their whole life. An identity install for the heart that was never broken, only waiting.",
    durationMinutes: 22,
    beatFrequency: 6,
    ambient: "rain",
    solfeggio: 639,
    phrases: [
      "I was never broken.",
      "I am already loved. I have always been loved.",
      "I do not have to earn what I was born with.",
      "My heart is safe to open now.",
      "The people who could not love me were not the measure of my lovability.",
      "I stop bracing for the withdrawal that was never coming.",
      "I am allowed to be chosen easily.",
      "I receive love the way a plant receives light.",
      "I am loved in the silences.",
      "My heart is not a fortress. It is a room with the door open.",
      "I am allowed to need. I am allowed to rest in being held.",
      "The love I have been looking for outside was always inside me too.",
      "I trust the people who show up without a test.",
      "I stop performing to be safe.",
      "I am soft and I am whole at the same time.",
      "The love I am now is the love I was before the fear.",
      "I do not apologize for needing the people I love.",
      "I am allowed to take up space in the hearts of the people who love me.",
      "I am loveable without proof.",
      "I release the story that love was going to run out.",
      "The love I have now does not have to be earned ever again.",
      "I am held by people I did not have to convince.",
      "My heart is open and my heart is safe.",
      "I was always enough. I was always enough. I was always enough.",
      "I come home to the heart that was never broken.",
    ],
  },

  {
    slug: "the-body-that-was-never-wrong",
    title: "The body that was never wrong",
    description:
      "For the person who has been at war with their body. A return to the body as a loyal ally that was only ever trying to protect you.",
    durationMinutes: 20,
    beatFrequency: 5,
    ambient: "forest",
    solfeggio: 528,
    phrases: [
      "My body was never the problem.",
      "My body has been loyal to me my entire life.",
      "Every symptom was a message I did not know how to read.",
      "My body is not my enemy. It never was.",
      "I trust what my body knows before my mind catches up.",
      "My body is safe in my own hands.",
      "I stop punishing my body for surviving.",
      "My body carried me through everything. I thank her.",
      "My body is allowed to rest now. She has done so much.",
      "I am friends with my body for the first time.",
      "I listen to the quiet signals before they become loud.",
      "I am allowed to be in my body without wanting it to be different.",
      "My body is a home, not a project.",
      "I trust my body to hold me.",
      "My body knows how to heal when I stop fighting her.",
      "The shapes my body takes are not moral.",
      "I release the story that I have to fix my body to be loved.",
      "My body was never wrong. It was only unheard.",
      "I am allowed to take care of my body the way I would a friend.",
      "I move my body because I love it, not to punish it.",
      "I eat from the body, not from the fear.",
      "My body is the only one I will ever have. I am choosing kindness.",
      "I am home inside my own skin.",
      "My body is safe. My body is loved. My body is mine.",
      "I come home to the body that was never wrong.",
    ],
  },

  {
    slug: "sleep-deeper-than-you-remember",
    title: "Sleep deeper than you remember",
    description:
      "A 30-minute sleep install. Put this on as you get into bed. The theta beats pull you down and the phrases land at the hypnagogic threshold.",
    durationMinutes: 30,
    beatFrequency: 4,
    ambient: "rain",
    phrases: [
      "My body is ready to rest now.",
      "I am safe to let go for the night.",
      "Sleep is coming to meet me.",
      "Every breath is softer than the last.",
      "My shoulders, my jaw, my belly — all of them are done for the day.",
      "I release every conversation I carried today.",
      "I release every decision that was mine to make.",
      "I release every person I was holding in my chest.",
      "My mind is allowed to stop now.",
      "Nothing requires my attention for the next eight hours.",
      "I trust the night to hold me.",
      "My body remembers how to sleep deeply.",
      "I drift down without resistance.",
      "The bed is holding me. The room is holding me. The night is holding me.",
      "I am safe in my own body, in my own bed, in my own room.",
      "Tomorrow will be there when I need it.",
      "I am allowed to rest without earning it.",
      "My cells are repairing as I drift.",
      "My dreams will carry what I do not need to hold awake.",
      "I fall deeper with every exhale.",
      "Sleep is not a performance. I do not have to try.",
      "I let myself be the one who gets to rest.",
      "My body is grateful for the stillness.",
      "Good night to the version of me that worked so hard today.",
      "Good night. Good night. I am home.",
    ],
  },

  {
    slug: "the-fear-release",
    title: "The fear release",
    description:
      "A 20-minute fear-release track at 396 Hz — the Solfeggio frequency associated with liberating fear. The ambient layer is ocean because the ocean never argues with what it is carrying.",
    durationMinutes: 20,
    beatFrequency: 5,
    ambient: "ocean",
    solfeggio: 396,
    phrases: [
      "The fear was a visitor. It is not my owner.",
      "I release the fear I inherited that was never mine.",
      "I release the fear that kept me smaller than I am.",
      "I release the fear of being seen.",
      "I release the fear of being loved.",
      "I release the fear of being left.",
      "I release the fear of being wrong.",
      "I release the fear of being too much.",
      "I release the fear of being not enough.",
      "Every fear I am letting go of is allowed to leave now.",
      "I thank the fear for protecting me when I was small.",
      "I do not need that protection anymore.",
      "The fear can rest. I will take it from here.",
      "My body is allowed to forget how to be afraid.",
      "I am safer now than I was when the fear was written.",
      "I release the fear that I was in danger when I am not.",
      "My nervous system is safe to soften.",
      "Each exhale releases another layer.",
      "I am not the fear. I am the one underneath it.",
      "The fear is smaller than I thought it was.",
      "I am bigger than the fear that lived inside me.",
      "I am allowed to live without the fear running me.",
      "I release. I release. I release.",
      "I am free. I am free. I am free.",
      "What remains when the fear leaves is me. And I am enough.",
    ],
  },
];

export function findSubliminal(slug: string): SubliminalTrack | null {
  return SUBLIMINALS.find((t) => t.slug === slug) ?? null;
}
